name: Tests
on:
  push:
    branches:
      - main

  release:
    types: [published]

  pull_request:

  workflow_dispatch:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Install packages
        run: |
          julia -e 'import Pkg;Pkg.add("SpecialFunctions");Pkg.add("NIfTI")'
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd test
          ./test_coreg.jl
          
